[package]
name = "auth-service"
version = "0.1.0"
edition = "2021"

[dependencies]
consul_utils.workspace = true
axum.workspace = true
sea-orm.workspace = true
tokio = { version = "1.36.0", features = ["full"] }
lazy_static = "1.4.0"
serde = "1.0.201"
anyhow = "1.0.83"

[dependencies.sea-orm-migration]
version = "0.12.0"
features = [
  # Enable at least one `ASYNC_RUNTIME` and `DATABASE_DRIVER` feature if you want to run migration via CLI.
  # View the list of supported features at https://www.sea-ql.org/SeaORM/docs/install-and-config/database-and-async-runtime.
  # e.g.
  "runtime-tokio-rustls",  # `ASYNC_RUNTIME` feature
  "sqlx-postgres",         # `DATABASE_DRIVER` feature
]
